#!/usr/bin/env bash

is_hdmi1_connected=$(xrandr | grep -e 'HDMI1 connected' | wc -l)

if [ "$is_hdmi1_connected" == "1" ]; then
    logger "$0 Enabling first screen (if case turned off)"
    $(xrandr --output eDP1 --off)

    logger "$0 Enabling HDMI1 screen."
    $(xrandr --output HDMI1 --auto)

    logger "$0 HDMI1 is connected. Setting HDMI1 to primary screen."
    $(xrandr --output HDMI1 --primary)
fi
